(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('game');
let gl;
try{gl=canvas.getContext('webgl',{antialias:true,alpha:false});}catch(e){}
if(!gl){$('loading').style.display='none';$('error').style.display='flex';$('error').innerHTML='<div class="errbox"><b>3D не запустился</b>Ваш браузер не дал странице доступ к WebGL. Откройте index.html в актуальном Chrome, Edge, Firefox или Safari.</div>';return;}
const vs=`attribute vec3 p;attribute vec3 c;attribute vec3 n;uniform mat4 mvp;uniform mat4 model;varying vec3 vc;varying vec3 vn;void main(){gl_Position=mvp*vec4(p,1.0);vc=c;vn=mat3(model)*n;}`;
const fs=`precision mediump float;varying vec3 vc;varying vec3 vn;void main(){vec3 L=normalize(vec3(-.45,1.0,.5));float d=max(dot(normalize(vn),L),0.0);gl_FragColor=vec4(vc*(.32+.68*d),1.0);}`;
function sh(t,s){let x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x}
let pr=gl.createProgram();gl.attachShader(pr,sh(gl.VERTEX_SHADER,vs));gl.attachShader(pr,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);if(!gl.getProgramParameter(pr,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(pr));gl.useProgram(pr);
const A={p:gl.getAttribLocation(pr,'p'),c:gl.getAttribLocation(pr,'c'),n:gl.getAttribLocation(pr,'n'),mvp:gl.getUniformLocation(pr,'mvp'),model:gl.getUniformLocation(pr,'model')};
const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
function M(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function T(x,y,z){let m=I();m[12]=x;m[13]=y;m[14]=z;return m}function S(x,y,z){let m=I();m[0]=x;m[5]=y;m[10]=z;return m}function RY(a){let m=I(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m}
function persp(f,a,n,far){let q=1/Math.tan(f/2),nf=1/(n-far),m=new Float32Array(16);m[0]=q/a;m[5]=q;m[10]=(far+n)*nf;m[11]=-1;m[14]=2*far*n*nf;return m}
function look(ex,ey,ez,cx,cy,cz){let zx=ex-cx,zy=ey-cy,zz=ez-cz,l=Math.hypot(zx,zy,zz);zx/=l;zy/=l;zz/=l;let xx=zy,xy=-zx;l=Math.hypot(xx,xy)||1;xx/=l;xy/=l;let yx=xy*zz,yy=-xx*zz,yz=xx*zy-xy*zx;let m=new Float32Array([xx,yx,zx,0,xy,yy,zy,0,0,yz,zz,0,0,0,0,1]);return M(m,T(-ex,-ey,-ez))}
function col(h){h=h.slice(1);return[parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255]}
function cube(x,y,z,sx,sy,sz,h){let cc=col(h),q=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]],f=[[0,1,2,3,0,0,-1],[4,7,6,5,0,0,1],[0,4,5,1,-1,0,0],[3,2,6,7,1,0,0],[0,3,7,4,0,-1,0],[1,5,6,2,0,1,0]],p=[],n=[],c=[],i=[];for(let zf of f){let b=p.length/3;for(let k of zf.slice(0,4)){p.push(x+q[k][0]*sx,y+q[k][1]*sy,z+q[k][2]*sz);n.push(zf[4],zf[5],zf[6]);c.push(...cc)}i.push(b,b+1,b+2,b,b+2,b+3)}return{p,n,c,i}}
function make(parts){let p=[],n=[],c=[],i=[],o=0;for(let a of parts){p.push(...a.p);n.push(...a.n);c.push(...a.c);i.push(...a.i.map(v=>v+o));o+=a.p.length/3}let b={};for(let [k,v] of [['p',p],['n',n],['c',c]]){b[k]=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b[k]);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.STATIC_DRAW)}b.i=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,b.i);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(i),gl.STATIC_DRAW);b.count=i.length;return b}
function draw(b,model,vp){gl.bindBuffer(gl.ARRAY_BUFFER,b.p);gl.enableVertexAttribArray(A.p);gl.vertexAttribPointer(A.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,b.n);gl.enableVertexAttribArray(A.n);gl.vertexAttribPointer(A.n,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,b.c);gl.enableVertexAttribArray(A.c);gl.vertexAttribPointer(A.c,3,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(A.model,false,model);gl.uniformMatrix4fv(A.mvp,false,M(vp,model));gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,b.i);gl.drawElements(gl.TRIANGLES,b.count,gl.UNSIGNED_SHORT,0)}
const W=260,H=210,parts=[];
parts.push(cube(0,-.5,0,W/2,.5,H/2,'#142126'));
for(let x=-120;x<=120;x+=26)parts.push(cube(x,.02,0,6,.025,H/2,'#252b2e'));
for(let z=-95;z<=95;z+=26)parts.push(cube(0,.025,z,W/2,.025,6,'#252b2e'));
const bcols=['#384b5a','#4b5359','#4e5c52','#5b4d47','#40556a'];
for(let x=-104;x<=104;x+=26)for(let z=-78;z<=78;z+=26){if(Math.abs(x)<20&&Math.abs(z)<20)continue;if(x>50&&z>30)continue;let h=8+Math.random()*25,w=8+Math.random()*7,d=8+Math.random()*7;parts.push(cube(x+(Math.random()-.5)*3,h/2,z+(Math.random()-.5)*3,w/2,d/2,h,bcols[(Math.random()*bcols.length)|0]))}
parts.push(cube(82,.0,-55,30,.08,22,'#0c3d4b'));const world=make(parts);
const beaconMesh=make([cube(0,.7,0,.25,.7,.25,'#ffd45d')]);
const playerMesh=make([cube(0,.9,0,.45,.9,.32,'#284a65'),cube(0,1.95,0,.33,.35,.33,'#bf8767'),cube(-.25,.05,0,.16,.45,.18,'#1e252b'),cube(.25,.05,0,.16,.45,.18,'#1e252b'),cube(.52,1.05,-.18,.15,.55,.13,'#284a65')]);
const npcMesh=make([cube(0,.75,0,.35,.75,.28,'#4f6650'),cube(0,1.55,0,.28,.3,.28,'#b47d5d'),cube(-.2,0,0,.12,.4,.14,'#25292d'),cube(.2,0,0,.12,.4,.14,'#25292d')]);
const carMesh=make([cube(0,.5,0,1.05,.5,2.05,'#8d3e45'),cube(0,1.05,-.25,.78,.38,1.0,'#17262e'),cube(-.82,.25,-1.25,.22,.25,.36,'#090b0d'),cube(.82,.25,-1.25,.22,.25,.36,'#090b0d'),cube(-.82,.25,1.25,.22,.25,.36,'#090b0d'),cube(.82,.25,1.25,.22,.25,.36,'#090b0d')]);
const key=new Set(),cars=[],npcs=[];let player={x:0,z:28,yaw:0,y:0},mode='third',inCar=false,car=null,camYaw=0,camPitch=.12,ammo=18,cash=2450,wanted=0,mission=0,target={x:80,z:52},jump=0,mouse=false,last=performance.now(),toastT=0;
for(let i=0;i<22;i++){let h=Math.random()<.5;let road=Math.round((Math.random()*7-3.5))*26;let along=Math.random()*230-115;cars.push({x:h?along:road,z:h?road:along,yaw:h?(Math.random()<.5?0:Math.PI):(Math.random()<.5?Math.PI/2:-Math.PI/2),speed:2+Math.random()*5})}
for(let i=0;i<35;i++)npcs.push({x:Math.random()*230-115,z:Math.random()*170-85,yaw:Math.random()*6.28,t:Math.random()*3,alive:true});
function resize(){canvas.width=Math.max(1,Math.floor(innerWidth*Math.min(devicePixelRatio||1,1.6)));canvas.height=Math.max(1,Math.floor(innerHeight*Math.min(devicePixelRatio||1,1.6)));gl.viewport(0,0,canvas.width,canvas.height)}addEventListener('resize',resize);resize();
function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;clearTimeout(toastT);toastT=setTimeout(()=>$('toast').style.opacity=0,1400)}
function fire(){if(inCar||ammo<=0)return;ammo--;$('ammo').textContent=ammo;wanted=Math.min(5,wanted+.2);let dx=Math.sin(camYaw),dz=Math.cos(camYaw),hit=null,best=30;for(let n of npcs){if(!n.alive)continue;let vx=n.x-player.x,vz=n.z-player.z,t=vx*dx+vz*dz,s=Math.abs(vx*dz-vz*dx);if(t>0&&t<best&&s<1.2){best=t;hit=n}}if(hit){hit.alive=false;cash+=75;$('cash').textContent='$'+cash.toLocaleString();toast('ЦЕЛЬ ПОРАЖЕНА +$75')}if(ammo===0){toast('ПЕРЕЗАРЯДКА');setTimeout(()=>{ammo=18;$('ammo').textContent=ammo},800)}}
function carToggle(){if(inCar){inCar=false;player.x=car.x+Math.sin(car.yaw)*3;player.z=car.z+Math.cos(car.yaw)*3;toast('ВЫШЛИ ИЗ АВТО');car=null;return}let near=null,d=4;for(let c of cars){let q=Math.hypot(c.x-player.x,c.z-player.z);if(q<d){d=q;near=c}}if(near){car=near;inCar=true;player.x=car.x;player.z=car.z;player.yaw=car.yaw;toast('АВТОМОБИЛЬ — УПРАВЛЕНИЕ')}}
function update(dt){if(inCar){let a=(key.has('KeyW')?1:0)-(key.has('KeyS')?1:0),s=(key.has('KeyD')?1:0)-(key.has('KeyA')?1:0);car.speed=Math.max(-7,Math.min(18,car.speed+a*13*dt));car.speed*=Math.pow(.97,dt*60);car.yaw+=s*(.45+Math.abs(car.speed)*.03)*dt;car.x+=Math.sin(car.yaw)*car.speed*dt;car.z+=Math.cos(car.yaw)*car.speed*dt;player.x=car.x;player.z=car.z;player.yaw=car.yaw}else{let a=(key.has('KeyD')?1:0)-(key.has('KeyA')?1:0),f=(key.has('KeyW')?1:0)-(key.has('KeyS')?1:0),l=Math.hypot(a,f);if(l){a/=l;f/=l;let F=[Math.sin(camYaw),Math.cos(camYaw)],R=[Math.cos(camYaw),-Math.sin(camYaw)],vx=F[0]*f+R[0]*a,vz=F[1]*f+R[1]*a,sp=key.has('ShiftLeft')||key.has('ShiftRight')?9:5.2;player.x+=vx*sp*dt;player.z+=vz*sp*dt;player.yaw=Math.atan2(vx,vz)}if(jump>0){jump-=dt;player.y=Math.sin((.6-jump)/.6*Math.PI)*1.05;if(jump<=0)player.y=0}}player.x=Math.max(-122,Math.min(122,player.x));player.z=Math.max(-97,Math.min(97,player.z));for(let c of cars){if(c===car)continue;c.x+=Math.sin(c.yaw)*c.speed*dt;c.z+=Math.cos(c.yaw)*c.speed*dt;if(Math.abs(c.x)>125||Math.abs(c.z)>100)c.yaw+=Math.PI}for(let n of npcs){if(!n.alive)continue;n.t-=dt;if(n.t<0){n.t=.8+Math.random()*2.5;n.yaw=Math.random()*6.28}n.x+=Math.sin(n.yaw)*1.3*dt;n.z+=Math.cos(n.yaw)*1.3*dt;if(Math.abs(n.x)>124||Math.abs(n.z)>99)n.yaw+=Math.PI}wanted=Math.max(0,wanted-dt*.012);mission=Math.min(1,mission+dt*.008);if(Math.hypot(player.x-target.x,player.z-target.z)<6){cash+=500;$('cash').textContent='$'+cash.toLocaleString();toast('ЗАДАНИЕ ВЫПОЛНЕНО +$500');target={x:Math.random()*220-110,z:Math.random()*160-80};mission=0}updateUI()}
function updateUI(){let near=cars.some(c=>Math.hypot(c.x-player.x,c.z-player.z)<4);$('prompt').style.display=near&&!inCar?'block':'none';$('wanted').textContent='★'.repeat(Math.ceil(wanted))+'☆'.repeat(5-Math.ceil(wanted));$('missionText').textContent=Math.hypot(player.x-target.x,player.z-target.z)<18?'Вы почти у цели — войдите в жёлтую зону':'Доберитесь до жёлтой отметки'}
function camera(){let focusX=player.x,focusZ=player.z;if(mode==='first'&&!inCar){let ex=focusX,ey=1.7+player.y,ez=focusZ,fx=Math.sin(camYaw)*Math.cos(camPitch),fy=Math.sin(camPitch),fz=Math.cos(camYaw)*Math.cos(camPitch);return{v:look(ex,ey,ez,ex+fx*20,ey+fy*20,ez+fz*20),px:ex,py:ey,pz:ez}}let d=inCar?9:7.5,h=inCar?3.8:3.1,side=inCar?0:1.15,ex=focusX-Math.sin(camYaw)*d+Math.cos(camYaw)*side,ez=focusZ-Math.cos(camYaw)*d-Math.sin(camYaw)*side,ey=player.y+h+Math.sin(camPitch)*d,tx=focusX+Math.sin(camYaw)*2,tz=focusZ+Math.cos(camYaw)*2;return{v:look(ex,ey,ez,tx,player.y+1.25,tz),px:ex,py:ey,pz:ez}}
function render(){gl.enable(gl.DEPTH_TEST);gl.clearColor(.025,.055,.07,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);let C=camera(),vp=M(persp(1.02,canvas.width/canvas.height,.1,420),C.v);draw(world,I(),vp);for(let c of cars)draw(carMesh,M(T(c.x,0,c.z),RY(c.yaw)),vp);for(let n of npcs)if(n.alive)draw(npcMesh,M(T(n.x,0,n.z),RY(n.yaw)),vp);if(!(mode==='first'&&!inCar))draw(playerMesh,M(T(player.x,player.y,player.z),RY(player.yaw)),vp);draw(beaconMesh,T(target.x,.1,target.z),vp)}
function map(){let c=$('map').getContext('2d'),w=180;c.fillStyle='#071018';c.fillRect(0,0,w,w);c.strokeStyle='#253139';c.lineWidth=4;for(let x=8;x<w;x+=18){c.beginPath();c.moveTo(x,0);c.lineTo(x,w);c.stroke()}for(let y=8;y<w;y+=18){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}c.fillStyle='#0d3f4e';c.fillRect(125,105,38,28);let px=(player.x/260+.5)*w,pz=(player.z/210+.5)*w,tx=(target.x/260+.5)*w,tz=(target.z/210+.5)*w;c.fillStyle='#ffd45d';c.beginPath();c.arc(tx,tz,4,0,7);c.fill();c.fillStyle='#8fd6ff';c.beginPath();c.arc(px,pz,4,0,7);c.fill()}
canvas.addEventListener('click',()=>canvas.requestPointerLock&&canvas.requestPointerLock());canvas.addEventListener('mousedown',e=>{if(e.button===0){mouse=true;fire()}});addEventListener('mouseup',e=>{if(e.button===0)mouse=false});addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas)camYaw+=e.movementX*.0028});addEventListener('keydown',e=>{key.add(e.code);if(e.code==='KeyV'){mode=mode==='third'?'first':'third';$('mode').textContent=mode==='third'?'3RD PERSON':'1ST PERSON';toast(mode==='third'?'КАМЕРА: ТРЕТЬЕ ЛИЦО':'КАМЕРА: ПЕРВОЕ ЛИЦО')}if(e.code==='KeyE'||e.code==='KeyF')carToggle();if(e.code==='Space'&&jump<=0&&!inCar)jump=.6});addEventListener('keyup',e=>key.delete(e.code));
function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;if(mouse)fire();update(dt);render();map();requestAnimationFrame(loop)}
setTimeout(()=>{$('loadText').textContent='Город готов. Запуск персонажа…'},250);setTimeout(()=>{$('loadText').textContent='Камера от третьего лица…'},500);setTimeout(()=>{$('loading').style.opacity=0;setTimeout(()=>$('loading').remove(),500);toast('VICE DISTRICT — ИГРА ЗАПУЩЕНА')},800);requestAnimationFrame(loop);
})();